export const VAULT_ERROR_CODES = {
  VAULT_NOT_FOUND: "VAULT_NOT_FOUND",
  VAULT_ITEM_NOT_FOUND: "VAULT_ITEM_NOT_FOUND",
  VAULT_MISSING_VAULT_ID: "VAULT_MISSING_VAULT_ID",
  VAULT_SAVE_FAILED: "VAULT_SAVE_FAILED",
  VAULT_CLEAR_FAILED: "VAULT_CLEAR_FAILED",
} as const

export type VaultErrorCode = (typeof VAULT_ERROR_CODES)[keyof typeof VAULT_ERROR_CODES]

export const EMBY_ERROR_CODES = {
  EMBY_DYNAMIC_WATCH_NOT_FOUND: "EMBY_DYNAMIC_WATCH_NOT_FOUND",
  EMBY_INVALID_DYNAMIC_WATCH: "EMBY_INVALID_DYNAMIC_WATCH",
  EMBY_DYNAMIC_WATCH_SAVE_FAILED: "EMBY_DYNAMIC_WATCH_SAVE_FAILED",
} as const

export type EmbyErrorCode = (typeof EMBY_ERROR_CODES)[keyof typeof EMBY_ERROR_CODES]

export const ACTIVITY_ERROR_CODES = {
  ACTIVITY_NOT_FOUND: "ACTIVITY_NOT_FOUND",
  ACTIVITY_DELETE_FAILED: "ACTIVITY_DELETE_FAILED",
} as const

export type ActivityErrorCode = (typeof ACTIVITY_ERROR_CODES)[keyof typeof ACTIVITY_ERROR_CODES]
