export const VAULT_ERROR_CODES = {
  VAULT_NOT_FOUND: "VAULT_NOT_FOUND",
  VAULT_ITEM_NOT_FOUND: "VAULT_ITEM_NOT_FOUND",
  VAULT_MISSING_VAULT_ID: "VAULT_MISSING_VAULT_ID",
  VAULT_SAVE_FAILED: "VAULT_SAVE_FAILED",
  VAULT_CLEAR_FAILED: "VAULT_CLEAR_FAILED",
} as const

export type VaultErrorCode = (typeof VAULT_ERROR_CODES)[keyof typeof VAULT_ERROR_CODES]
